language: java
install: true

addons:
  sonarcloud:
    organization: "ivandalbosco-github"

jdk:
  - oraclejdk8

script:
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report package sonar:sonar
  - mvn clean package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
